Added grammars and inputs both correct and incorrect for dynamic tests
FormalLanguageConstrainedPathQuerying/UCFS pull request #20
Opened 2024-03-22 15:57 UTC by cyb3r-b4stard

2024-04-11 09:56 UTC, bachish requested changes
Хорошие изменения кода! 
Комментарии тоже хорошие и содержательные. Только в следующий раз стоит делать их отдельным изменением в стабильную ветку. Потому что сейчас нам предстоит ужасное слияние веток. 

Жду исправлений! 
И предлагаю merge делать совместно, чтобы случайно не испортить измненеия друг друга.

2024-04-11 09:56 UTC, bachish commented on .gitignore
> +src/main/kotlin/org/antlr/Java8Parser.java
В .gitignore и папка antlr, и файлы внутри нее. Избыточно.
И нужна ли нам глобально в main antlr для  java8?

2024-04-11 09:56 UTC, bachish commented on .gitignore
>  /src/main/kotlin/org/srcgll/lexer/*.java
Аналогично, не лучше ли вынести это из main в конкретный тест? Можно не динамический.

2024-04-11 09:56 UTC, bachish commented on Demos/grammars.tex
Имя папки с прописной буквы

2024-04-11 09:56 UTC, bachish commented on Demos/grammars.tex
В tex рисовать полезно. Но зачем такой специфичный файл в проекте? 
Автоматически ли он генерируется?

2024-04-11 09:56 UTC, bachish commented on build.gradle.kts
> +    implementation("org.antlr:antlr4:4.13.1")
Стоит вынести сборку для бенчмарков отдельно, чтобы парсер не тянул в себе все эти зависимости.

2024-04-11 09:56 UTC, bachish commented on build.gradle.kts
> +}
тоже в отдельную сборку

2024-04-11 09:56 UTC, bachish commented on gradle.properties
> +org.gradle.jvmargs=-Xmx4096m -Xss4m -XX:+UseG1GC
И это в отдельную сборку!

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/Example.kt
>  fun main() {
А зачем оставлять метод с пустым телом?

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/Main.kt
>  }
Старые артефакты

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/Main.kt
> +    val input: String = File(pathToInput).readText()
Стоит вынести всю эту логику в отдельный тест

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/descriptors/DescriptorsStorage.kt
> +     * @param vertex - vertex in input graph
Товарищу, который будет заниматься инкрементальностью, сделует вынести это в отдельный интерфейс.
Пока пусть будет. Завела issue

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/grammar/combinator/regexp/Alternative.kt
> +fun Option(exp: String) = Alternative.makeAlternative(Epsilon, Term(exp))
Не стоит добавлять логику для конкретного типа в общий класс Alternative. 
Для каждого типа эти методы нужно реализовывать в отдельном файле. 
Если это наш тип -- то в нем самом.
Расширения для строк уже есть в cf_solver в файле src/main/kotlin/org/srcgll/grammar/combinator/extension/StringExtension.kt, нужно аккуратно мержить.

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/grammar/combinator/regexp/Concatenation.kt
> +infix operator fun String.times(other: String): Concat = Concat(head = Term(this), Term(other))
Аналогичное замечание про extension.

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/grammar/combinator/regexp/Many.kt
> +fun Some(exp: String) = Term(exp) * Many(Term(exp))
Аналогичное замечание про extension.

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/gss/GssNode.kt
> +     * Nonterminal A, corresponding to grammar slot of the form aA·b
А если это слот после терминала?

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/input/RecoveryLinearInput.kt
> +}
Код никак не отличается от аналогичного в LinearInput, кроме первого конструктора. 
Стоит вынести общую логику.

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/lexer/Java.x
Стоит вынетси в тесты

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/lexer/JavaGrammar.kt
В тесты

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/lexer/JavaGrammarScannerless.kt
В тесты

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/lexer/JavaToken.kt
> -    GREATEQ, INSTANCEOF, RIGHTSHIT, LEFTSHIFT, USRIGHTSHIFT, SYNCHRONIZED, NATIVE, VOID,
Забавная опечатка))

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/parser/generator/GeneratedParser.kt
> +        val curSppfNode = ctx.sppf.getEpsilonSppfNode(descriptor)
Почему epsilonSppf?

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/parser/generator/GeneratedParser.kt
> +        }
??

2024-04-11 09:56 UTC, bachish commented on src/main/kotlin/org/srcgll/sppf/Sppf.kt
> -     * @return ParentNode
Почему удалено дополнительное описание? Это не самая очевидная часть.

2024-04-11 09:56 UTC, bachish commented on src/test/kotlin/dynamic/parser/generator/GllGeneratedTest.kt
Файл закомментирован.

2024-04-11 09:56 UTC, bachish commented on src/test/kotlin/dynamic/parser/generator/RuntimeCompiler.kt
Файл закомментирован.

2024-04-11 09:58 UTC, bachish commented on Demos/grammars.tex
Если нет, то стоит убрать это из проекта.

2024-04-11 10:10 UTC, cyb3r-b4stard commented on .gitignore
> +src/main/kotlin/org/antlr/Java8Parser.java
Я специально в папке antlr выделил все файлы, которые генерируются, а оставил файл для грамматики. В main наверное antlr нужен только для бенчмрков, чтобы оттуда класс парсера тянуть. В релизной версии стоит убрать

2024-04-11 10:13 UTC, cyb3r-b4stard commented on Demos/grammars.tex
Да, это все не нужно нам. Вся папка Demos была создана единожды, чтобы примеры инкрементальности показать. Это все лишнее

2024-04-11 10:18 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/Main.kt
>  }
Уберу

2024-04-11 10:20 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/grammar/combinator/regexp/Alternative.kt
> +fun Option(exp: String) = Alternative.makeAlternative(Epsilon, Term(exp))
Это я хотфикс писал, чтобы грамматики со строковыми терминалами по проще работали. Если в основной ветке уже нормальный вариант есть, то этот при мердже можно убрать

2024-04-11 10:22 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/gss/GssNode.kt
> +     * Nonterminal A, corresponding to grammar slot of the form aA·b
Это не может быть слот после терминала, GssNode всегда отвечает нетерминалу. Все терминальные слоты разбираются в соотв. GssNode с нетерминальным слотом

2024-04-11 10:23 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/input/RecoveryLinearInput.kt
> +}
Я пытался, но там проблема есть с типизацией, поэтому это было простое решение. Там нужно аккуратно посмотреть, в лоб - не работает

2024-04-11 10:24 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/lexer/JavaToken.kt
> -    GREATEQ, INSTANCEOF, RIGHTSHIT, LEFTSHIFT, USRIGHTSHIFT, SYNCHRONIZED, NATIVE, VOID,
Ахахаххаха, поправлю)

2024-04-11 10:24 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/parser/generator/GeneratedParser.kt
> +        val curSppfNode = ctx.sppf.getEpsilonSppfNode(descriptor)
Потому что он отвечает выводу эпсилон-строки

2024-04-11 10:26 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/sppf/Sppf.kt
> -     * @return ParentNode
Я решил что вдаваться в детали реализации пользователю не нужно, достаточно понимать, что принципиально метод делает

2024-04-12 09:21 UTC, bachish commented on src/main/kotlin/org/srcgll/parser/generator/GeneratedParser.kt
> +        }
GeneratedParser -- это базовый класс для генерируемых парсеров. Сам он не генерируется.

2024-04-12 09:23 UTC, bachish commented on build.gradle.kts
> +    implementation("org.antlr:antlr4:4.13.1")
Точно поддерживает, но сама так собирать не пробовала.

2024-04-12 09:24 UTC, bachish commented on src/main/kotlin/org/srcgll/sppf/Sppf.kt
> -     * @return ParentNode
Все таки верни эту часть. Ничего плохого в качественном описании нет, пользователь может его просто игнорировать.
Во antlr, например, тоже детали реализации подробно описываются в доках к классам и методам. Причем эти доки часто больше самих классов и методов.

2024-04-12 09:26 UTC, bachish commented on src/main/kotlin/org/srcgll/parser/generator/GeneratedParser.kt
> +        }
Сгенерированные парсеры я совсем не добавляю в репозиторий.

2024-04-12 09:27 UTC, bachish commented on src/main/kotlin/org/srcgll/parser/generator/GeneratedParser.kt
> +        val curSppfNode = ctx.sppf.getEpsilonSppfNode(descriptor)
Стоит добавить комментарий! 
Потому что мне на первый взгляд показалось, что epsilonSppfNode -- какой-то новый хитрый вид ноды в дереве.

2024-04-12 09:27 UTC, bachish commented on src/main/kotlin/org/srcgll/parser/generator/GeneratedParser.kt
> +        val curSppfNode = ctx.sppf.getEpsilonSppfNode(descriptor)
Ну или переименовать в SppfNodeForEpsilon

2024-04-12 14:53 UTC, bachish approved these changes
Все ок, лексер java8 поправлю

2024-04-12 14:54 UTC, merged