CF solver incrementality
FormalLanguageConstrainedPathQuerying/UCFS pull request #5
Opened 2023-11-22 13:03 UTC by cyb3r-b4stard

2023-11-28 10:58 UTC, bachisheo commented
Разреши конфликты, пожалуйтса

2023-12-06 14:30 UTC, gsvgit commented on src/main/kotlin/org/srcgll/Example.kt
> +        S = Many(
Честно говоря, исходный вариант приятнее читать было.

2023-12-06 14:30 UTC, gsvgit commented on src/main/kotlin/org/srcgll/Example.kt
> +    override val terminal: Terminal<String>? = when (label) {
Зачем такое форматирование? Это в Котлине так принято?

2023-12-06 14:30 UTC, gsvgit commented on src/main/kotlin/org/srcgll/GLL.kt
> +    private fun minDistance(root: ISPPFNode): Int {
Это же работа с SPPF. Зачем она прям тут?

2023-12-06 14:32 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/Example.kt
> +    override val terminal: Terminal<String>? = when (label) {
Да, Оля настояла чтобы мы писали в едином стиле, принятом для Kotlin

2023-12-06 14:33 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/GLL.kt
> +    private fun minDistance(root: ISPPFNode): Int {
Согласен, я как раз только что это перенес в sppf

2023-12-07 08:39 UTC, gsvgit commented
И снова конфликты какие-то. Порешите их, пожалуйста.

2023-12-07 11:17 UTC, cyb3r-b4stard commented
Что, что, что, какие конфликты, у меня все хорошо, показывает никаких конфликтов и можно безопасно мержить

2023-12-07 12:14 UTC, gsvgit commented
> Что, что, что, какие конфликты, у меня все хорошо, показывает никаких конфликтов и можно безопасно мержить

А... Это потому что я прошу его попробовать автоматически заребейзить. А Вам доступна кнопка про мёрж? Там в ней можно выбрать другой режим.

2023-12-23 10:07 UTC, bachisheo requested changes
Оставила замечания. В основном мелкие, по аккуратности кода. Есть два пожелания в общем:

1. Крупные методы выносить в функции с осмысленными названиями.
2. Обращать внимание на ворнинги idea,  чинить их.

2023-12-25 16:38 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/Example.kt
> +    writeSPPFToDOT(resultAnBn.first!!, "./srcgll/lol.dot")
Этих строчек вообще быть не должно, я это использовал для отладки десяти-минутной и забыл поправить

2023-12-25 16:45 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/GLL.kt
>          var rightExtent = curSPPFNode?.rightExtent
Я обращаюсь к ним ниже через !! в конкретном случае, когда состояние стартовое и финальное, потому что тогда я руками создаю новое состояние в дереве разбора => leftExtent и rightExtent что-то хранят, в иных же случаях дескриптор может иметь null-значение, а следовательно максимум что мы можем - безопасно обратиться через оператор Элвиса

2023-12-25 16:53 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/descriptors/DescriptorsStack.kt
> +    val hashCode = 23 * (23 * (23 * 17 + rsmState.hashCode()) + inputPosition.hashCode()) + gssNode.hashCode()
Не знаю, я это из F# версии перенес. Глобально можно переопределить хэши для всего, но я пока не видел в этом необходимости

2023-12-25 17:00 UTC, cyb3r-b4stard commented on src/main/kotlin/org/srcgll/Example.kt
> +    }
Тогда наследование ломается

2023-12-25 17:45 UTC, merged